
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ert.java
 *
 * Created on Feb 18, 2016, 12:47:23 AM
 */

/**
 *
 * @author Vivek K
 */
public class ert extends javax.swing.JFrame {

    /** Creates new form ert */
    public ert() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        b = new javax.swing.JCheckBox();
        a = new javax.swing.JCheckBox();
        c = new javax.swing.JCheckBox();
        list = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt.setEditable(false);
        txt.setFont(new java.awt.Font("Tahoma", 0, 18));
        txt.setText("I am TextField");

        btn.setText(" I am Button");

        lbl.setFont(new java.awt.Font("Tahoma", 0, 18));
        lbl.setText("I am Label");

        b.setText("Apply on Button");

        a.setText("Apply on Label");

        c.setText("Apply on Textfield");

        list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green", "Blue", " " }));
        list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listItemStateChanged(evt);
            }
        });
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b)
                            .addComponent(a)
                            .addComponent(c))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt)
                            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn)
                        .addGap(18, 18, 18)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listItemStateChanged
        // TODO add your handling code here:
}//GEN-LAST:event_listItemStateChanged

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
switch(list.getSelectedIndex()){
    case 0 :{
        if (a.isSelected())
        {
lbl.setForeground(Color.RED);
    }
    if (b.isSelected())
    {
    btn.setForeground(Color.RED);
    }
        if (c.isSelected())
        {
        txt.setForeground(Color.RED);
        }
    }
            break;
    case 1 :{
    if (a.isSelected())
    {
    lbl.setForeground(Color.GREEN);
    }
    if (b.isSelected())
    {
    btn.setForeground(Color.GREEN);
    }
    if (c.isSelected())
    {
    txt.setForeground(Color.GREEN);
    }
    }
    break;

    case 2 : {
    if (a.isSelected())
    {
    lbl.setForeground(Color.BLUE);
    }
    if (b.isSelected())
    {
    btn.setForeground(Color.BLUE);
    }
    if (c.isSelected())
    {
    txt.setForeground(Color.BLUE);
    }
    }
    break;
}        // TODO add your handling code here:
}//GEN-LAST:event_listActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox a;
    private javax.swing.JCheckBox b;
    private javax.swing.JButton btn;
    private javax.swing.JCheckBox c;
    private javax.swing.JLabel lbl;
    private javax.swing.JComboBox list;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables

}
